version: '3'
services:
  database:
    image: "postgres:11-alpine" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
            - /media/postgres-data/postgres/main/data:/var/lib/postgresql/data # persist data even if container shuts down

              #volumes:
              #database-data: # named volumes can be managed easier using docker-compose
