version: '3'
services:
  database:
    image: "postgres:9.3-alpine" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/media/postgres-data/postgres/main # persist data even if container shuts down
    
volumes:
  database-data: # named volumes can be managed easier using docker-compose
